PUT HTTP://localhost:3003/api/blogs/63db84f05cff65aceeef72fd
Content-Type: application/json

{
    "title": "Logic Tutorial part 2",
    "author": "John Smith",
    "url": "tutorials.com/logic",
    "likes": 10083,
    "user": "63da8b927f4ce966d49d30bf"
}